
name: API Tests et d√©ploiement

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Test/requirements.txt
          pip install pytest pytest-html

      - name: Check joblib version
        run: |
          python -c "import joblib; print('joblib version:', joblib.__version__)"

      - name: List files in Data folder
        run: |
          ls -l Output/Pipelines

      - name: Check if pipeline file exists
        run: |
          if [ -f Output/Pipelines/pipeline_to_deployed.joblib ]; then
              echo "Pipeline file exists, checking hash..."
              sha256sum Output/Pipelines/pipeline_to_deployed.joblib
          else
              echo "Pipeline file not found!"
              exit 1
          fi

      - name: Run API tests with HTML report
        run: |
          pytest -v --html=rapport_tests.html --self-contained-html Test/test_api.py

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: rapport-tests-html
          path: rapport_tests.html

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    - name: Install API dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r API/requirements.txt

    - name: Deploy API on Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID_API }}
      run: |
        curl -X POST "https://api.render.com/deploy/srv-${SERVICE_ID}" \
        -H "Accept: application/json" \
        -H "Authorization: Bearer ${RENDER_API_KEY}"

    - name: Install Streamlit dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Streamlit/requirements.txt

    - name: Deploy Streamlit on Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID_STREAMLIT }}
      run: |
        curl -X POST "https://api.render.com/deploy/srv-${SERVICE_ID}" \
        -H "Accept: application/json" \
        -H "Authorization: Bearer ${RENDER_API_KEY}"  
